---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
        - name: insurance
          image: pratheep04/medicure:1.0
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"

